global:
  log_file: /var/log/ob-panel.log
  debug: true #{true|false}

server:
  listen_port: 5000
  process_num: 2
  use_reloader: false

ftp:
  listen_port: 2121

websocket:
  listen_port: 5001

circus:
  end_port: 5002
