version: 2

output: prefixed

vars:
  BIN: obs
tasks:
  test:
    prefix: "test"
    cmds:
      - go test -v ./...
  build:
    prefix: "build"
    cmds:
      - go build -o {{.BIN}} ./cmd/obs
  dev:
    prefix: "dev"
    cmds:
      - rm -rf _dev/bin
      - mkdir -p _dev/bin
      - task: build
        vars: {BIN: _dev/bin/obs}
      - ./_dev/bin/obs
