version: 2

output: prefixed

vars:
  BIN: obs
tasks:
  test:
    prefix: "test"
    cmds:
      - go test -v ./...
  build:
    prefix: "build"
    cmds:
      - go build -o {{.BIN}} ./cmd/obs
  dev:
    prefix: "dev"
    cmds:
      - rm -rf _dev/build
      - mkdir -p _dev/build
      - task: build
        vars: {BIN: _dev/build/obs}
      - ./_dev/build/obs
  'migrate:new':
    prefix: "migration"
    cmds:
      - go run _dev/cli/main.go migrate:new {{.NAME}}
