// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginPayload struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginPayload) Reset()         { *m = LoginPayload{} }
func (m *LoginPayload) String() string { return proto.CompactTextString(m) }
func (*LoginPayload) ProtoMessage()    {}
func (*LoginPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_48464f71b56a36c9, []int{0}
}
func (m *LoginPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginPayload.Unmarshal(m, b)
}
func (m *LoginPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginPayload.Marshal(b, m, deterministic)
}
func (dst *LoginPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginPayload.Merge(dst, src)
}
func (m *LoginPayload) XXX_Size() int {
	return xxx_messageInfo_LoginPayload.Size(m)
}
func (m *LoginPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginPayload.DiscardUnknown(m)
}

var xxx_messageInfo_LoginPayload proto.InternalMessageInfo

func (m *LoginPayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ErrorReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Info                 []byte   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorReply) Reset()         { *m = ErrorReply{} }
func (m *ErrorReply) String() string { return proto.CompactTextString(m) }
func (*ErrorReply) ProtoMessage()    {}
func (*ErrorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_48464f71b56a36c9, []int{1}
}
func (m *ErrorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorReply.Unmarshal(m, b)
}
func (m *ErrorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorReply.Marshal(b, m, deterministic)
}
func (dst *ErrorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorReply.Merge(dst, src)
}
func (m *ErrorReply) XXX_Size() int {
	return xxx_messageInfo_ErrorReply.Size(m)
}
func (m *ErrorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorReply.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorReply proto.InternalMessageInfo

func (m *ErrorReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ErrorReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *ErrorReply) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *ErrorReply) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

type LoginResponse struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_48464f71b56a36c9, []int{2}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type LoginReply struct {
	// Types that are valid to be assigned to SuccessOrFail:
	//	*LoginReply_Resp
	//	*LoginReply_Error
	SuccessOrFail        isLoginReply_SuccessOrFail `protobuf_oneof:"SuccessOrFail"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_48464f71b56a36c9, []int{3}
}
func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (dst *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(dst, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

type isLoginReply_SuccessOrFail interface {
	isLoginReply_SuccessOrFail()
}

type LoginReply_Resp struct {
	Resp *LoginResponse `protobuf:"bytes,1,opt,name=resp,proto3,oneof"`
}

type LoginReply_Error struct {
	Error *ErrorReply `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*LoginReply_Resp) isLoginReply_SuccessOrFail() {}

func (*LoginReply_Error) isLoginReply_SuccessOrFail() {}

func (m *LoginReply) GetSuccessOrFail() isLoginReply_SuccessOrFail {
	if m != nil {
		return m.SuccessOrFail
	}
	return nil
}

func (m *LoginReply) GetResp() *LoginResponse {
	if x, ok := m.GetSuccessOrFail().(*LoginReply_Resp); ok {
		return x.Resp
	}
	return nil
}

func (m *LoginReply) GetError() *ErrorReply {
	if x, ok := m.GetSuccessOrFail().(*LoginReply_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LoginReply) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _LoginReply_OneofMarshaler, _LoginReply_OneofUnmarshaler, _LoginReply_OneofSizer, []interface{}{
		(*LoginReply_Resp)(nil),
		(*LoginReply_Error)(nil),
	}
}

func _LoginReply_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*LoginReply)
	// SuccessOrFail
	switch x := m.SuccessOrFail.(type) {
	case *LoginReply_Resp:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Resp); err != nil {
			return err
		}
	case *LoginReply_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("LoginReply.SuccessOrFail has unexpected type %T", x)
	}
	return nil
}

func _LoginReply_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*LoginReply)
	switch tag {
	case 1: // SuccessOrFail.resp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginResponse)
		err := b.DecodeMessage(msg)
		m.SuccessOrFail = &LoginReply_Resp{msg}
		return true, err
	case 2: // SuccessOrFail.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ErrorReply)
		err := b.DecodeMessage(msg)
		m.SuccessOrFail = &LoginReply_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _LoginReply_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*LoginReply)
	// SuccessOrFail
	switch x := m.SuccessOrFail.(type) {
	case *LoginReply_Resp:
		s := proto.Size(x.Resp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *LoginReply_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*LoginPayload)(nil), "LoginPayload")
	proto.RegisterType((*ErrorReply)(nil), "ErrorReply")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*LoginReply)(nil), "LoginReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	Login(ctx context.Context, in *LoginPayload, opts ...grpc.CallOption) (*LoginReply, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Login(ctx context.Context, in *LoginPayload, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/AccountService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Login(context.Context, *LoginPayload) (*LoginReply, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Login(ctx, req.(*LoginPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AccountService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_login_48464f71b56a36c9) }

var fileDescriptor_login_48464f71b56a36c9 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x93, 0x7f, 0x93, 0xf2, 0xef, 0xa4, 0xa9, 0xb2, 0x07, 0x09, 0xc5, 0x43, 0x8d, 0x0a,
	0x3d, 0xe5, 0x10, 0x0f, 0xde, 0x04, 0x15, 0xa5, 0x07, 0x41, 0xd9, 0x7e, 0x82, 0x35, 0x19, 0x35,
	0x25, 0xee, 0x2c, 0xbb, 0xa9, 0xa5, 0xdf, 0x5e, 0x76, 0x0c, 0x46, 0xc1, 0xdb, 0xbc, 0x99, 0xf7,
	0x76, 0x7e, 0x3b, 0x90, 0xb4, 0xf4, 0xda, 0xe8, 0xc2, 0x58, 0xea, 0x28, 0xbf, 0x82, 0xe9, 0x83,
	0x97, 0x4f, 0x6a, 0xdf, 0x92, 0xaa, 0x85, 0x80, 0x48, 0xab, 0x77, 0xcc, 0xc2, 0x45, 0xb8, 0x9c,
	0x48, 0xae, 0xc5, 0x1c, 0xfe, 0x1b, 0xe5, 0xdc, 0x8e, 0x6c, 0x9d, 0xfd, 0xe3, 0xfe, 0xb7, 0xce,
	0x37, 0x00, 0x77, 0xd6, 0x92, 0x95, 0x68, 0xda, 0xfd, 0x9f, 0xe9, 0x63, 0x98, 0xa0, 0x77, 0xdc,
	0x52, 0x8d, 0x1c, 0x8f, 0xe5, 0xd0, 0x10, 0x47, 0x30, 0xae, 0xb1, 0x53, 0x4d, 0x9b, 0x8d, 0x38,
	0xd3, 0x2b, 0xff, 0x52, 0xa3, 0x5f, 0x28, 0x8b, 0x16, 0xe1, 0x72, 0x2a, 0xb9, 0xce, 0x4f, 0x20,
	0x65, 0x56, 0x89, 0xce, 0x90, 0x76, 0x28, 0x0e, 0x61, 0xb4, 0xd9, 0x75, 0xfd, 0x36, 0x5f, 0xe6,
	0x6f, 0x00, 0xbd, 0xc5, 0xe3, 0x9c, 0x41, 0x64, 0xd1, 0x19, 0x36, 0x24, 0xe5, 0xac, 0xf8, 0x95,
	0x5e, 0x05, 0x92, 0xa7, 0xe2, 0x14, 0x62, 0xe6, 0x61, 0xb8, 0xa4, 0x4c, 0x8a, 0xe1, 0x43, 0xab,
	0x40, 0x7e, 0xcd, 0x6e, 0x0e, 0x20, 0x5d, 0x6f, 0xab, 0x0a, 0x9d, 0x7b, 0xb4, 0xf7, 0xaa, 0x69,
	0xcb, 0x4b, 0x98, 0x5d, 0x57, 0x15, 0x6d, 0x75, 0xb7, 0x46, 0xfb, 0xd1, 0x54, 0x28, 0xce, 0x21,
	0xe6, 0x05, 0x22, 0x2d, 0x7e, 0x9e, 0x74, 0x9e, 0x14, 0x03, 0x52, 0x1e, 0x3c, 0x8f, 0xf9, 0xf0,
	0x17, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x24, 0x3d, 0xe3, 0x87, 0x01, 0x00, 0x00,
}
